### ISSUE TITLE
Incorrect directory name

### ISSUE THREAD

**Issue by jheaff1** [Karry/osmscout-scripts#4]
Hi,

I am using the scripts in this repository to host my own osmscout server.

I have a working server that contains a few random countries for testing: andorra, cyprus and ireland-and-northern-ireland.

The list of available maps provided by the `AvailableMapsModel` in libosmscout is:

```
ireland-and-northern-ireland / androrra
ireland-and-northern-ireland / cyprus
ireland-and-northern-ireland / ireland-and-northern-ireland
```

I would expect that the list should be

```
europe / androrra
europe / cyprus
europe / ireland-and-northern-ireland
```

The JSON returned from running ` curl http://<URL of my map server>/latest.php?` is 

```json
[{"map":"europe\/andorra","version":19,"directory":"europe\/andorra-19-20210824-1054","timestamp":1629798841,"size":1813437,"name":"andorra"},{"map":"europe\/cyprus","version":19,"directory":"europe\/cyprus-19-20210824-1054","timestamp":1629798861,"size":26356305,"name":"cyprus"},{"map":"europe\/ireland-and-northern-ireland","version":19,"directory":"europe\/ireland-and-northern-ireland-19-20210824-1059","timestamp":1629799167,"size":284581539,"name":"ireland-and-northern-ireland"},{"dir":"europe","name":"ireland-and-northern-ireland"}]
```

Notice the field:

```json
{"dir":"europe","name":"ireland-and-northern-ireland"}
```

Whereas the JSON returned from running `curl https://osmscout.karry.cz/latest.php?` contains the following field:

```json
{"dir":"europe","name":"Europe"}
```

May I ask how to set up the map server so that the JSON returned by querying `latest.php` contains the correct directories?
Perhaps the invocation of `gc.sh` does this?

https://github.com/Karry/osmscout-scripts/blob/411c5652a815f7fb6e535080e5320e48af5d4f58/build-europe.sh#L74

There is no `gc.sh` stored in the repository though

**Comment by Karry** [comment]
Hi. 

The garbage collector script (`gc.sh`) just invokes `cleanup.php` script on the server with the secret. Its purpose is to search map directories that no longer exists, and mark them as deleted in database... It was missing in the repository, thank you for report. I [added it here](https://github.com/Karry/osmscout-scripts/commit/9a0aad0f396ef200675822d00059fb8ba4a3ec58).

Name of your europe "directory" is really incorrect. Can you execute SQL query `SELECT * FROM l10n WHERE path = 'europe' ;` ? Or do you have this table empty?

**Comment by Karry** [comment]
Which PHP version do you have on the server?

**Comment by Karry** [comment]
I found the bug, this commit should fix it: https://github.com/Karry/osmscout-scripts/commit/b66705aeb9e067ac45a707404a28ec2a154f25e4 

Please let me know if it working for you.

**Comment by jheaff1** [comment]
Yep that works now, thank you very much indeed for your help!
